version: '3.8'

services:
  voice_service:
    build:
      context: .
      dockerfile: Dockerfile.voice_service
    container_name: voice_service
    ports:
      - "8888:8888"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge 