version: '3.8'

services:
  voice_service:
    build:
      context: .
      dockerfile: Dockerfile.voice_service
    container_name: voice_service
    ports:
      - "8888:8888"
    networks:
      - appnet

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: tcp_client
    depends_on:
      - voice_service
    environment:
      - SERVER_HOST=voice_service
      - SERVER_PORT=8888
    networks:
      - appnet

networks:
  appnet:
    driver: bridge 